parameters:
     pim_delta_export.reader.doctrine.product.class: Pim\Bundle\DeltaExportBundle\Reader\ProductReader

services:
    pim_delta_export.reader.doctrine.product:
        class: %pim_delta_export.reader.doctrine.product.class%
        parent: pim_base_connector.reader.doctrine.product
        arguments:
            - @pim_delta_export.manager.product_export
