parameters:
     pim_delta_export.reader.doctrine.product.class: Pim\Bundle\DeltaExportBundle\Reader\ProductReader
     pim_base_connector.reader.doctrine.obsoleteproduct.class: Pim\Bundle\BaseConnectorBundle\Reader\Doctrine\ObsoleteProductReader

services:
    pim_delta_export.reader.doctrine.product:
        class: %pim_delta_export.reader.doctrine.product.class%
        parent: pim_base_connector.reader.doctrine.obsoleteproduct
        arguments:
            - @pim_delta_export.manager.product_export
    pim_delta_export.reader.doctrine.product_value:
        class: %pim_delta_export.reader.doctrine.product.class%
        parent: pim_base_connector.reader.doctrine.product
        arguments:
            - @pim_delta_export.manager.product_value_export

    pim_base_connector.reader.doctrine.obsoleteproduct:
        class: %pim_base_connector.reader.doctrine.obsoleteproduct.class%
        arguments:
            - '@pim_catalog.repository.product'
            - '@pim_catalog.manager.channel'
            - '@pim_catalog.manager.completeness'
            - '@pim_transform.converter.metric'
